site_name: ADCPDataProcessing.jl
repo_url: https://github.com/wkearn/ADCPDataProcessing.jl
site_description: Documentation for ADCPDataProcessing.jl
site_author: Will Kearney

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Home: index.md
